name: HotPotato
main: cn.lanink.hotpotato.HotPotato
version: "1.0.3-PM1E"
api: ["Nukkit-PM1E"]
load: POSTWORLD
author: "LT_Name"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"
  - "AutoUpData"
loadbefore:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"
  - "AutoUpData"

permissions:
  HotPotato.command.user:
    default: true
  HotPotato.command.admin:
    default: op