name: HotPotato
main: cn.lanink.hotpotato.HotPotato
version: "1.2.0-PM1E"
api: ["Nukkit-PM1E"]
load: POSTWORLD
author: "LT_Name"
depend:
  - "MemoriesOfTime-GameCore"

permissions:
  HotPotato.command.user:
    default: true
  HotPotato.command.admin:
    default: op