name: HotPotato
main: cn.lanink.hotpotato.HotPotato
version: "1.0.2-SNAPSHOT"
api:
  - 1.0.0
load: POSTWORLD
author: "LT_Name"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"
  - "AutoUpData"
loadbefore:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"
  - "AutoUpData"

permissions:
  HotPotato.command.user:
    default: true
  HotPotato.command.admin:
    default: op